// Code generated by go-swagger; DO NOT EDIT.

// Package restapi aws-cli
//
//  Run AWS CLI commands in direktiv
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
