// Code generated by go-swagger; DO NOT EDIT.

// Package restapi image-magick
//
//  Description for image-magick
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
